server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
springdoc:
  api-docs:
    path: /api-docs
management:
  server:
    port: 8081
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

jwt:
  jwt-secret: 59fedfab-9fa7-4a33-9ea0-c76e7729009a
  jwt-expiration-ms: 86400000

---

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootstrap
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  config:
    activate:
      on-profile: local-postgresql

---

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    activate:
      on-profile: heroku-postgresql