server:
  port: ${PORT:8080}

spring:
  devtools:
    add-properties: false
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
springdoc:
  api-docs:
    path: /api-docs
management:
  server:
    port: 8081
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true

jwt:
  jwt-secret: 59fedfab-9fa7-4a33-9ea0-c76e7729009a
  jwt-expiration-ms: 86400000
---

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootstrap
    username: postgres
    password: postgres
  config:
    activate:
      on-profile: local-postgresql

---

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    activate:
      on-profile: heroku-postgresql