### Create user
POST http://localhost:8080/security/signup
Content-Type: application/json

{
  "email": "test@test.com.br",
  "username": "test",
  "password": "test"
}

### User login
POST http://localhost:8080/security/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

> {% client.global.set("auth_token", response.body); %}


### Fetch information about me using the token
GET http://localhost:8080/security/me
Authorization: Bearer {{auth_token}}
