name: Run snky for security coverage
on:
  pull_request:
    branches: [ main ]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-9-jdk24@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}